export const GAME_CONFIG = {
  // Runtime paths resolve to imported Texture2D assets in the resources bundle.
  designWidth: 750,
  designHeight: 1334,
  boardSize: 4,
  swipeThreshold: 42,
  moveSeconds: 0.12,
  mergeSeconds: 0.2,
  cats: [
    { level: 1, name: '橘猫', asset: 'game/cats/cat_01/texture' },
    { level: 2, name: '蓝白英短', asset: 'game/cats/cat_02/texture' },
    { level: 3, name: '三花猫', asset: 'game/cats/cat_03/texture' },
    { level: 4, name: '布偶猫', asset: 'game/cats/cat_04/texture' },
    { level: 5, name: '暹罗猫', asset: 'game/cats/cat_05/texture' },
    { level: 6, name: '美短虎斑', asset: 'game/cats/cat_06/texture' },
    { level: 7, name: '奶牛猫', asset: 'game/cats/cat_07/texture' },
    { level: 8, name: '孟买黑猫', asset: 'game/cats/cat_08/texture' },
    { level: 9, name: '银河极光猫', asset: 'game/cats/cat_09/texture' },
  ],
  art: {
    homeBackground: 'game/backgrounds/bg_home/texture',
    pageBackground: 'game/backgrounds/bg_page/texture',
    boardBackground: 'game/backgrounds/bg_board_wood/texture',
    shareScoreBackground: 'game/backgrounds/share_score_bg/texture',
    tileBase: 'game/gameplay/tile_empty/texture',
    tileSelected: 'game/gameplay/tile_selected/texture',
    sparkleSmall: 'game/gameplay/sparkle_small/texture',
    mergeSparkle: 'game/gameplay/merge_sparkle/texture',
    mergeBurst: 'game/gameplay/merge_burst/texture',
    maxHalo: 'game/gameplay/max_halo/texture',
    close: 'game/ui/close/texture',
    back: 'game/ui/back/texture',
    home: 'game/ui/home/texture',
    check: 'game/ui/check/texture',
    share: 'game/ui/share/texture',
    soundOn: 'game/ui/sound_on/texture',
    soundOff: 'game/ui/sound_off/texture',
    settings: 'game/ui/settings/texture',
    info: 'game/ui/info/texture',
  },
  fonts: {
    display: 'game/fonts/display',
  },
} as const;
