export const GAME_CONFIG = {
  // Runtime paths resolve to imported Texture2D assets in the resources bundle.
  designWidth: 750,
  designHeight: 1334,
  boardSize: 4,
  swipeThreshold: 42,
  moveSeconds: 0.12,
  mergeSeconds: 0.2,
  cats: [
    { level: 1, name: '橘猫', description: '爱晒太阳，也爱把棋盘占得满满当当。', asset: 'game/cats/cat_01/texture' },
    { level: 2, name: '蓝白英短', description: '圆脸短腿，认真守着每一次合成。', asset: 'game/cats/cat_02/texture' },
    { level: 3, name: '三花猫', description: '花色独一无二，运气也总是很好。', asset: 'game/cats/cat_03/texture' },
    { level: 4, name: '布偶猫', description: '温柔安静，像一团会呼吸的云。', asset: 'game/cats/cat_04/texture' },
    { level: 5, name: '暹罗猫', description: '好奇又健谈，什么动静都逃不过它。', asset: 'game/cats/cat_05/texture' },
    { level: 6, name: '美短虎斑', description: '精力十足，最擅长把局面重新盘活。', asset: 'game/cats/cat_06/texture' },
    { level: 7, name: '奶牛猫', description: '黑白分明，行动却永远出人意料。', asset: 'game/cats/cat_07/texture' },
    { level: 8, name: '孟买黑猫', description: '像一小片夜色，安静又神秘。', asset: 'game/cats/cat_08/texture' },
    { level: 9, name: '银河极光猫', description: '星光落在毛尖，是进化路线的终点。', asset: 'game/cats/cat_09/texture' },
  ],
  art: {
    logo: 'game/branding/logo/texture',
    homeBackground: 'game/backgrounds/bg_home/texture',
    pageBackground: 'game/backgrounds/bg_page/texture',
    boardBackground: 'game/backgrounds/bg_board_wood/texture',
    shareScoreBackground: 'game/backgrounds/share_score_bg/texture',
    tileBase: 'game/gameplay/tile_empty/texture',
    tileSelected: 'game/gameplay/tile_selected/texture',
    sparkleSmall: 'game/gameplay/sparkle_small/texture',
    mergeSparkle: 'game/gameplay/merge_sparkle/texture',
    mergeBurst: 'game/gameplay/merge_burst/texture',
    maxHalo: 'game/gameplay/max_halo/texture',
    close: 'game/ui/close/texture',
    back: 'game/ui/back/texture',
    home: 'game/ui/home/texture',
    check: 'game/ui/check/texture',
    share: 'game/ui/share/texture',
    soundOn: 'game/ui/sound_on/texture',
    soundOff: 'game/ui/sound_off/texture',
    settings: 'game/ui/settings/texture',
    info: 'game/ui/info/texture',
    locked: 'game/ui/locked/texture',
  },
  fonts: {
    display: 'game/fonts/display',
    numbers: 'game/fonts/score',
  },
} as const;
