import { CAT_DEFINITIONS } from './catDefinitions';

export const GAME_CONFIG = {
  // Runtime paths resolve to imported Texture2D assets in the resources bundle.
  designWidth: 750,
  designHeight: 1334,
  boardSize: 4,
  swipeThreshold: 42,
  moveSeconds: 0.12,
  mergeSeconds: 0.2,
  cats: CAT_DEFINITIONS,
  network: {
    // 排行榜服务地址：接入新环境时只需改这里（或替换为环境配置）。
    leaderboardBaseUrl: 'https://hongshu.sale/wx_server',
  },
  art: {
    logo: 'game/ui/common/logo/texture',
    homeBackground: 'game/ui/home-v2/home_background_v2/texture',
    homeCatRoom: 'game/ui/home-v2/home_cat_room/texture',
    homePlayPaw: 'game/ui/home-v2/home_play_paw/texture',
    homeBottomDock: 'game/ui/home-v2/home_bottom_dock/texture',
    homeCollection: 'game/ui/home-v2/collection/texture',
    homeShop: 'game/ui/home-v2/shop/texture',
    homeTasks: 'game/ui/home-v2/tasks/texture',
    homeSettings: 'game/ui/home-v2/settings/texture',
    homeCoin: 'game/ui/home-v2/coin/texture',
    homePlus: 'game/ui/home-v2/plus/texture',
    homeLeaderboardButton: 'game/ui/home-v2/leaderboard_button/texture',
    homeCheckinButton: 'game/ui/home-v2/checkin_button/texture',
    collectionBackground: 'game/ui/collection/collection_background/texture',
    collectionCardLight: 'game/ui/collection/collection_card_light/texture',
    collectionCardLocked: 'game/ui/collection/collection_card_locked/texture',
    collectionBackPaw: 'game/ui/collection/collection_back_paw/texture',
    collectionLockedCat: 'game/ui/collection/collection_locked_cat/texture',
    collectionLock: 'game/ui/collection/collection_lock/texture',
    pageBackground: 'game/backgrounds/common/bg_page/texture',
    boardBackground: 'game/backgrounds/board/wood/bg_board_wood/texture',
    gameplayStatsSheet: 'game/ui/gameplay/stats_sprite_sheet/texture',
    shareScoreBackground: 'game/backgrounds/common/share_score_bg/texture',
    tileBase: 'game/ui/common/tile_empty/texture',
    tileSelected: 'game/ui/common/tile_selected/texture',
    sparkleSmall: 'game/effects/classic/sparkle_small/texture',
    mergeSparkle: 'game/effects/classic/merge_sparkle/texture',
    mergeBurst: 'game/effects/classic/merge_burst/texture',
    maxHalo: 'game/effects/classic/max_halo/texture',
    close: 'game/ui/common/close/texture',
    back: 'game/ui/common/back/texture',
    home: 'game/ui/common/home/texture',
    check: 'game/ui/common/check/texture',
    classicMode: 'game/ui/common/classic_mode/texture',
    restart: 'game/ui/common/restart/texture',
    collection: 'game/ui/common/collection/texture',
    undo: 'game/ui/common/undo/texture',
    removeLowest: 'game/ui/common/remove_lowest/texture',
    coin: 'game/ui/common/coin/texture',
    share: 'game/ui/common/share/texture',
    soundOn: 'game/ui/common/sound_on/texture',
    soundOff: 'game/ui/common/sound_off/texture',
    settings: 'game/ui/common/settings/texture',
    info: 'game/ui/common/info/texture',
    locked: 'game/ui/common/locked/texture',
  },
  fonts: {
    display: 'game/fonts/display',
  },
} as const;
